app-version: v1.0.0
app-name: Hero Backend

server:
  port: 2001
  compression: # GZIP
    min-response-size: 1024
    enabled: true
    mime-types: application/json
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:h2:mem:hero_db;DB_CLOSE_DELAY=-1
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  h2:
    console:
      enabled: true

# Swagger
springdoc:
  pre-loading-enabled: true # False in production
  swagger-ui:
    operationsSorter: alpha
    enabled: true # False in production
    path: /swagger-ui.html
  override-with-generic-response: false
  api-docs:
    enabled: true # False in production