app-version: v1.0.0
app-name: Hero Backend

server:
  port: 2001

spring:
  datasource:
    url: jdbc:h2:mem:hero_db;DB_CLOSE_DELAY=-1
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  h2:
    console:
      enabled: true